In [1]:
import numpy as np

In [4]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [13]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [16]:
a[2] = 10

In [18]:
a

array([ 1,  2, 10,  5,  7, 12])

In [21]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [25]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [27]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
n = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9 ]])

In [35]:
n[0,1] = 20

In [37]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [39]:
n[2] = [1,1,1]

In [41]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [46]:
n[:,2] = [5,5,5]

In [48]:
n

array([[ 1, 20,  5],
       [ 4,  5,  5],
       [ 1,  1,  5]])

In [99]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [ ]:
np.random.seed(2)
np.random.randn(5,2)

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [101]:
np.random.seed(2)
np.random.randint(0, 100, (5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [103]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [111]:
b = (10 + (a * 2)) ** 2 / 100

In [112]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [115]:
a*b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [117]:
a >= 2

array([False, False,  True,  True,  True])

In [119]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [121]:
a > b

array([False, False,  True,  True,  True])

In [123]:
a[a > b]

array([2, 3, 4])

In [127]:
a.min()

np.int64(0)